# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
